### ISSUE TITLE
SVG格式错误

### ISSUE THREAD

**Issue by Johnsonzcode** [cran/RIdeogram#1]
尊敬的作者：
你好！我在画图过程中发现SVG文件打不开，打开后是xml的格式并没有出现图画，转化为PNG也是出错只转化了一部分。
这是这两个文件。
![image](https://user-images.githubusercontent.com/40168263/159720031-726657e6-228f-43d6-8ffe-9f14dde08e8b.png)

![image](https://user-images.githubusercontent.com/40168263/159720838-f280d1cf-e121-479d-8980-e6166cff628d.png)

期望的图是中间有共线性线条的

希望作者大大帮帮忙~

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
